#!/usr/bin/env python3
"""Encode the diamond weasel PNG file bytes into an XOR-encrypted C header.

Route: write-on-first-unlock. The PNG bytes are embedded in the DLL as
XOR-encrypted data so the image cannot be extracted from the DLL before a
real unlock. On first unlock the mod decrypts the bytes and writes them to
the game's Textures\\ folder, then the game loads them through its normal
file path.

Usage:
    diamond_png_encode.py <out_header.h> <medal.png> <mini.png>
"""
import sys

XORKEY = 0x5A


def block(data, name, key):
    lines = []
    lines.append(f"/* {name} — XOR-encrypted PNG bytes (key 0x{key:02X}) */")
    lines.append(f"static const unsigned char {name}_data[] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"#define {name}_SIZE   (sizeof({name}_data))")
    lines.append(f"#define {name}_XORKEY 0x{key:02X}")
    lines.append("")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)
    out, medal_png, mini_png = sys.argv[1], sys.argv[2], sys.argv[3]
    medal = open(medal_png, "rb").read()
    mini = open(mini_png, "rb").read()
    em = bytes(b ^ XORKEY for b in medal)
    im = bytes(b ^ XORKEY for b in mini)
    with open(out, "w") as f:
        f.write("/* AUTO-GENERATED by diamond_png_encode.py — do not edit. */\n")
        f.write("/* Embeds the diamond weasel PNG bytes as XOR-encrypted data. */\n\n")
        f.write(block(em, "diamondweasel_png", XORKEY))
        f.write(block(im, "diamondweasel_icon_png", XORKEY))
    print(f"wrote {out}: medal {len(medal)}B, mini {len(mini)}B (encrypted)")


if __name__ == "__main__":
    main()