#!/usr/bin/env python3
"""Encode diamond weasel PNG(s) into XOR-encrypted raw A8R8G8B8 C headers.

Route 2 (fully in-memory): the PNG is decoded at BUILD time to raw 32-bit
BGRA pixels, XOR-encrypted with a key, and emitted as a C array. The DLL
decrypts in memory and builds a D3D texture directly — NO PNG ever ships,
no decrypted bytes ever touch disk at runtime.
"""
import struct, sys, zlib
from PIL import Image

KEY = 0x5A5A5A5A  # arbitrary XOR key (kept in the DLL at runtime)

def png_to_raw(path):
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    # A8R8G8B8 little-endian = bytes B,G,R,A (D3D A8R8G8B8)
    raw = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b, a = im.getpixel((x, y))
            raw += struct.pack('<BBBB', b, g, r, a)  # BGRA
    return w, h, bytes(raw)

def xor_encrypt(data, key):
    k = struct.pack('<I', key)
    out = bytearray(len(data))
    for i in range(len(data)):
        out[i] = data[i] ^ k[i & 3]
    return bytes(out)

def emit_header(name, w, h, enc, key):
    lines = []
    lines.append(f"/* AUTO-GENERATED by diamond_encode.py — do not edit. */")
    lines.append(f"/* Encrypted raw A8R8G8B8 pixels for {name}. */")
    lines.append(f"/* Dimensions: {w}x{h}, XOR key 0x{key:08X}. No PNG data present. */")
    lines.append(f"#define {name}_WIDTH   {w}")
    lines.append(f"#define {name}_HEIGHT  {h}")
    lines.append(f"#define {name}_XORKEY  0x{key:08X}ul")
    lines.append(f"static const unsigned char {name}_data[] = {{")
    for i in range(0, len(enc), 16):
        chunk = enc[i:i+16]
        hexs = ', '.join(f'0x{b:02X}' for b in chunk)
        lines.append(f"    {hexs}," if i+16 < len(enc) else f"    {hexs}")
    lines.append(f"}};")
    lines.append(f"#define {name}_SIZE (sizeof({name}_data))")
    return "\n".join(lines) + "\n"

def main():
    if len(sys.argv) < 3:
        print("usage: diamond_encode.py <out_header.h> <png1> [png2 ...]")
        return 1
    out = sys.argv[1]
    parts = []
    for png in sys.argv[2:]:
        w, h, raw = png_to_raw(png)
        enc = xor_encrypt(raw, KEY)
        base = png.rsplit('/',1)[-1].rsplit('.',1)[0].replace('-','_').replace(' ','_')
        parts.append(f"/* ==== {png} ==== */")
        parts.append(emit_header(base, w, h, enc, KEY))
        print(f"  {png}: {w}x{h}, {len(raw)} raw bytes -> {len(enc)} enc bytes")
    with open(out, 'w') as f:
        f.write("\n".join(parts))
    print(f"wrote {out}")
    return 0

if __name__ == '__main__':
    sys.exit(main())