#!/usr/bin/env python3
"""
recon-analyzer.py — A small, non-target-specific first-pass analyzer for compiled binaries.

Usage:
    python3 recon-analyzer.py /path/to/binary [options]
    python3 recon-analyzer.py /path/to/binary --format md --out report.md
    python3 recon-analyzer.py /path/to/dir   --recursive --out report.md
"""

import argparse
import hashlib
import json
import math
import os
import re
import subprocess
import sys
from pathlib import Path

try:
    import pefile
except ImportError:
    pefile = None


def entropy(data: bytes) -> float:
    if not data:
        return 0.0
    counts = [0] * 256
    for b in data:
        counts[b] += 1
    total = len(data)
    ent = 0.0
    for c in counts:
        if c == 0:
            continue
        p = c / total
        ent += p * math.log2(p)
    return -ent


def hash_file(path: Path):
    with open(path, "rb") as f:
        data = f.read()
    return {
        "md5": hashlib.md5(data).hexdigest(),
        "sha256": hashlib.sha256(data).hexdigest(),
        "size": len(data),
        "entropy": entropy(data),
    }


def strings_from(path: Path, min_len: int = 4) -> list:
    try:
        raw = subprocess.check_output(["strings", "-n", str(min_len), str(path)], text=True, errors="replace")
        return raw.splitlines()
    except Exception as e:
        return [f"<strings failed: {e}>"]


def categorize_strings(lines: list) -> dict:
    cats = {
        "urls": [l for l in lines if re.search(r"https?://", l)],
        "paths": [l for l in lines if re.search(r"[A-Za-z]:\\|\\|/", l)],
        "dlls": [l for l in lines if re.search(r"\.dll$", l, re.IGNORECASE)],
        "apis": [l for l in lines if re.search(
            r"direct3d|d3d|directinput|dinput|dsound|bass|winmm|ws2_32|opengl|vulkan|sdl|glfw|openal|xinput",
            l, re.IGNORECASE)],
        "file_types": [l for l in lines if re.search(
            r"\.(exe|dll|sys|so|dylib|mesh|world|xml|json|cfg|ini|txt|wav|ogg|mp3|png|bmp|jpg|ttf|otf|fnt|mo3|mod|s3m)$",
            l, re.IGNORECASE)],
        "interesting": [l for l in lines if re.search(
            r"password|secret|key|token|admin|root|debug|error|fatal|crash|version|copyright|license",
            l, re.IGNORECASE)],
    }
    return {k: sorted(set(v))[:100] for k, v in cats.items()}


def pe_summary(path: Path) -> dict:
    if pefile is None:
        return {"error": "pefile not installed"}
    try:
        pe = pefile.PE(str(path))
        sections = [
            {
                "name": s.Name.decode(errors="replace").strip("\x00"),
                "rva": hex(s.VirtualAddress),
                "virtual_size": hex(s.Misc_VirtualSize),
                "raw_size": hex(s.SizeOfRawData),
                "entropy": round(s.get_entropy(), 3),
            }
            for s in pe.sections
        ]
        imports = []
        if hasattr(pe, "DIRECTORY_ENTRY_IMPORT"):
            for entry in pe.DIRECTORY_ENTRY_IMPORT:
                imports.append({
                    "dll": entry.dll.decode(),
                    "count": len(entry.imports),
                    "first_few": [i.name.decode() if i.name else f"ordinal_{i.ordinal}" for i in entry.imports[:5]],
                })
        exports = []
        if hasattr(pe, "DIRECTORY_ENTRY_EXPORT"):
            exports = [e.name.decode() if e.name else str(e.ordinal) for e in pe.DIRECTORY_ENTRY_EXPORT.symbols[:20]]
        return {
            "arch": "x64" if pe.PE_TYPE == 0x20B else "x86",
            "image_base": hex(pe.OPTIONAL_HEADER.ImageBase),
            "entry_point_rva": hex(pe.OPTIONAL_HEADER.AddressOfEntryPoint),
            "subsystem": pe.OPTIONAL_HEADER.Subsystem,
            "sections": sections,
            "imports": imports,
            "exports": exports,
        }
    except Exception as e:
        return {"error": str(e)}


def analyze_file(path: Path) -> dict:
    result = {"path": str(path)}
    result.update(hash_file(path))
    result["strings"] = categorize_strings(strings_from(path))
    result["pe"] = pe_summary(path)
    return result


def to_md(report: dict) -> str:
    lines = ["# Recon Analyzer Report", ""]
    target = report["target"]
    lines += [f"**Target:** `{target}`", f"**Generated by:** recon-analyzer.py", ""]
    for item in report["files"]:
        lines += [f"## {item['path']}", ""]
        lines += [
            f"- **Size:** {item['size']} bytes",
            f"- **MD5:** `{item['md5']}`",
            f"- **SHA256:** `{item['sha256']}`",
            f"- **Entropy:** {item['entropy']:.3f}",
            "",
        ]
        if not item["pe"].get("error"):
            pe = item["pe"]
            lines += [
                "### PE Summary",
                f"- **Architecture:** {pe['arch']}",
                f"- **Image base:** {pe['image_base']}",
                f"- **Entry point RVA:** {pe['entry_point_rva']}",
                f"- **Subsystem:** {pe['subsystem']}",
                "",
                "#### Sections",
                "| Name | RVA | Virtual Size | Raw Size | Entropy |",
                "|------|-----|--------------|----------|---------|",
            ]
            for s in pe["sections"]:
                lines.append(f"| {s['name']} | {s['rva']} | {s['virtual_size']} | {s['raw_size']} | {s['entropy']} |")
            lines.append("")
            if pe["imports"]:
                lines += ["#### Imports", ""]
                for imp in pe["imports"]:
                    lines.append(f"- `{imp['dll']}` ({imp['count']} imports) — {', '.join(imp['first_few'])}")
                lines.append("")
            if pe["exports"]:
                lines += ["#### Exports", ""]
                for e in pe["exports"]:
                    lines.append(f"- `{e}`")
                lines.append("")
        for cat, vals in item["strings"].items():
            if vals:
                lines += [f"### Strings: {cat}", ""]
                for v in vals[:30]:
                    lines.append(f"- `{v}`")
                lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="First-pass binary reconnaissance analyzer")
    parser.add_argument("target", help="File or directory to analyze")
    parser.add_argument("-r", "--recursive", action="store_true", help="Recurse into directories")
    parser.add_argument("-f", "--format", choices=["json", "md"], default="md", help="Output format")
    parser.add_argument("-o", "--out", help="Output file (default: stdout)")
    parser.add_argument("--max-files", type=int, default=50, help="Max files to analyze in a directory")
    args = parser.parse_args()

    target = Path(args.target)
    files = []
    if target.is_file():
        files = [target]
    elif target.is_dir():
        if args.recursive:
            files = list(target.rglob("*"))
        else:
            files = [p for p in target.iterdir() if p.is_file()]
        files = files[:args.max_files]
    else:
        print(f"Target not found: {target}", file=sys.stderr)
        return 1

    report = {"target": str(target.resolve()), "files": [analyze_file(f) for f in files if f.is_file()]}
    if args.format == "json":
        output = json.dumps(report, indent=2)
    else:
        output = to_md(report)

    if args.out:
        with open(args.out, "w") as f:
            f.write(output)
        print(f"Wrote report to {args.out}")
    else:
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
